window.RE_ARCHIVE = {
  games: [
    { id:'re0', code:'00', year:'2002', title:'Resident Evil 0', era:'Origins', summary:'Rebecca Chambers and Billy Coen uncover an early chapter of the Umbrella conspiracy aboard the Ecliptic Express.', tags:['Rebecca','Umbrella','Arklay','T-Virus'], image:'https://cdn.akamai.steamstatic.com/steam/apps/339340/header.jpg', imagePosition:'50% 45%' },
    { id:'re1', code:'01', year:'1996', title:'Resident Evil', era:'Mansion Incident', summary:'S.T.A.R.S. investigates murders near Raccoon City and discovers the horrors hidden inside the Spencer Mansion.', tags:['Jill','Chris','Wesker','Spencer Mansion'], image:'https://cdn.akamai.steamstatic.com/steam/apps/4249100/header.jpg', imagePosition:'50% 48%' },
    { id:'re2', code:'02', year:'1998', title:'Resident Evil 2', era:'Raccoon City', summary:'Leon S. Kennedy and Claire Redfield arrive during the catastrophic Raccoon City outbreak.', tags:['Leon','Claire','R.P.D.','G-Virus'], image:'https://cdn.akamai.steamstatic.com/steam/apps/4249110/header.jpg', imagePosition:'50% 45%' },
    { id:'re3', code:'03', year:'1999', title:'Resident Evil 3', era:'Raccoon City', summary:'Jill Valentine attempts to escape Raccoon City while being hunted by Nemesis.', tags:['Jill','Nemesis','Raccoon City','U.B.C.S.'], image:'https://cdn.akamai.steamstatic.com/steam/apps/4249120/header.jpg', imagePosition:'50% 38%' },
    { id:'recv', code:'CV', year:'2000', title:'Code: Veronica', era:'Aftermath', summary:'Claire Redfield’s search for Chris leads to another Umbrella-linked nightmare far from Raccoon City.', tags:['Claire','Chris','Wesker','Umbrella'], image:'https://i.jeuxactus.com/datas/jeux/r/e/resident-evil-code-veronica-x/xl/resident-evil-code-4e26073a612d4.jpg', imagePosition:'50% 28%' },
    { id:'re4', code:'04', year:'2005', title:'Resident Evil 4', era:'Plaga Incident', summary:'Leon travels to rural Europe and encounters Los Illuminados and the parasitic Las Plagas.', tags:['Leon','Ada','Las Plagas','Europe'], image:'https://cdn.akamai.steamstatic.com/steam/apps/254700/header.jpg', imagePosition:'50% 42%' },
    { id:'re5', code:'05', year:'2009', title:'Resident Evil 5', era:'Global Bioterror', summary:'Chris Redfield and Sheva Alomar investigate a bioterror incident tied to a familiar enemy.', tags:['Chris','Wesker','B.S.A.A.','Uroboros'], image:'https://cdn.akamai.steamstatic.com/steam/apps/21690/header.jpg', imagePosition:'50% 42%' },
    { id:'re6', code:'06', year:'2012', title:'Resident Evil 6', era:'Global Bioterror', summary:'Multiple protagonists face a worldwide series of bioterror attacks involving the C-virus.', tags:['Leon','Chris','Ada','C-Virus'], image:'https://cdn.akamai.steamstatic.com/steam/apps/221040/header.jpg', imagePosition:'50% 44%' },
    { id:'re7', code:'07', year:'2017', title:'Resident Evil 7 biohazard', era:'Mold Incident', summary:'Ethan Winters searches for his missing wife inside the isolated Baker estate in Louisiana.', tags:['Ethan','Mia','Baker Estate','Mold'], image:'https://cdn.akamai.steamstatic.com/steam/apps/418370/header.jpg', imagePosition:'50% 48%' },
    { id:'re8', code:'08', year:'2021', title:'Resident Evil Village', era:'Village Incident', summary:'Ethan’s story continues in a remote European village ruled by dangerous and mysterious figures.', tags:['Ethan','Village','Mutamycete','B.S.A.A.'], image:'https://cdn.akamai.steamstatic.com/steam/apps/1196590/header.jpg', imagePosition:'50% 42%' },
    { id:'re2r', code:'2R', year:'2019', title:'Resident Evil 2 Remake', era:'Reimagined Raccoon City', summary:'A modern reimagining of Leon and Claire’s first night in Raccoon City.', tags:['Leon','Claire','Mr. X','R.P.D.'], image:'https://cdn.akamai.steamstatic.com/steam/apps/883710/header.jpg', imagePosition:'50% 46%' },
    { id:'re4r', code:'4R', year:'2023', title:'Resident Evil 4 Remake', era:'Reimagined Plaga Incident', summary:'Leon’s rescue mission returns with a darker, more grounded take on the European incident.', tags:['Leon','Ashley','Ada','Las Plagas'], image:'https://cdn.akamai.steamstatic.com/steam/apps/2050650/header.jpg', imagePosition:'50% 43%' }
  ],
  characters: [
    { id:'jill', file:'STARS-001', name:'Jill Valentine', role:'S.T.A.R.S. / B.S.A.A.', status:'Active', first:'Resident Evil', summary:'Veteran survivor of the Spencer Mansion incident and one of the franchise’s defining anti-bioterror operatives.', bio:'Jill survives the Arklay Mansion incident, helps expose Umbrella’s crimes, escapes the destruction of Raccoon City, and later becomes a central figure in international anti-bioterror operations.', image:'https://cdn.capcom-unity.com/2026/02/Raccoon-City-lovers_nero-Final-1024x576.jpg', imagePosition:'35% 50%', incidents:['Spencer Mansion','Raccoon City','Kijuju'], affiliations:['S.T.A.R.S.','B.S.A.A.'] },
    { id:'leon', file:'RPD-021', name:'Leon S. Kennedy', role:'R.P.D. / Federal Agent', status:'Active', first:'Resident Evil 2', summary:'A rookie police officer during the Raccoon City outbreak who later becomes an elite federal agent.', bio:'Leon arrives in Raccoon City for his first day on the police force and is immediately thrown into the citywide outbreak. His survival leads to a career handling some of the world’s most dangerous bioterror incidents.', image:'https://cdn.capcom-unity.com/2023/11/Leon-Claire-iryukxx-Final-1024x1024.jpg', imagePosition:'50% 25%', incidents:['Raccoon City','Los Illuminados','Tall Oaks'], affiliations:['R.P.D.','U.S. Government'] },
    { id:'claire', file:'CIV-019', name:'Claire Redfield', role:'TerraSave', status:'Active', first:'Resident Evil 2', summary:'A Raccoon City survivor whose search for Chris draws her into Umbrella’s experiments and later humanitarian work.', bio:'Claire enters Raccoon City while looking for her brother Chris. After surviving the outbreak, she becomes a prominent advocate for victims of bioterror and continues crossing paths with major outbreaks.', image:'https://cdn.capcom-unity.com/2023/11/Leon-Claire-Juli__Gamer-Final-1024x754.jpg', imagePosition:'50% 45%', incidents:['Raccoon City','Rockfort Island','Harvardville'], affiliations:['TerraSave'] },
    { id:'chris', file:'BSAA-005', name:'Chris Redfield', role:'S.T.A.R.S. / B.S.A.A.', status:'Active', first:'Resident Evil', summary:'A survivor of the mansion incident and longtime combatant against Umbrella and global bioterrorism.', bio:'Chris begins as a member of S.T.A.R.S. Alpha Team and becomes one of the longest-serving protagonists in the series, repeatedly confronting large-scale B.O.W. threats around the world.', image:'https://cdn.capcom-unity.com/2026/04/Stars-juniaxe-Final-1024x576.jpg', imagePosition:'50% 45%', incidents:['Spencer Mansion','Kijuju','Edonia'], affiliations:['S.T.A.R.S.','B.S.A.A.'] },
    { id:'ada', file:'UNKNOWN', name:'Ada Wong', role:'Classified Operative', status:'Unknown', first:'Resident Evil 2', summary:'An elusive intelligence operative whose missions repeatedly intersect with Leon and major biohazard incidents.', bio:'Ada’s employers and loyalties are deliberately obscured. She repeatedly appears at the center of high-value biological weapons operations, often pursuing samples while maintaining her own agenda.', image:'https://cdn.capcom-unity.com/2026/02/Survivors-juniaxe-Final-1024x576.jpg', imagePosition:'58% 45%', incidents:['Raccoon City','Los Illuminados','Tall Oaks'], affiliations:['Classified'] },
    { id:'wesker', file:'UMB-000', name:'Albert Wesker', role:'Umbrella / Classified', status:'Deceased', first:'Resident Evil', summary:'Former S.T.A.R.S. captain whose ambitions place him at the center of numerous biological conspiracies.', bio:'Wesker infiltrates S.T.A.R.S. while secretly serving Umbrella interests. His pursuit of viral power and control turns him into one of the franchise’s most persistent antagonists.', image:'https://cdn.capcom-unity.com/2026/04/Stars-juniaxe-Final-1024x576.jpg', imagePosition:'76% 40%', incidents:['Spencer Mansion','Rockfort Island','Kijuju'], affiliations:['Umbrella','S.T.A.R.S.'] },
    { id:'ethan', file:'CIV-E001', name:'Ethan Winters', role:'Civilian', status:'Classified', first:'Resident Evil 7', summary:'A civilian pulled into a biological nightmare while searching for his missing wife, Mia.', bio:'Ethan’s search for Mia brings him to the Baker estate and exposes him to the Mold. His story later expands into the European village incident and the truth behind the Winters family.', image:'https://image.zeta-ai.io/profile-image/9b179ad8-e2e7-437b-85d1-20b7e25636d5/268a4e3a-469f-47dd-a719-ab30934dc7c7.jpeg', imagePosition:'50% 20%', incidents:['Baker Estate','Village'], affiliations:['Civilian'] },
    { id:'carlos', file:'UBCS-003', name:'Carlos Oliveira', role:'U.B.C.S.', status:'Unknown', first:'Resident Evil 3', summary:'A mercenary deployed during the Raccoon City disaster who becomes an important ally to Jill Valentine.', bio:'Carlos arrives as part of Umbrella’s Biohazard Countermeasure Service. As the disaster unfolds, he rejects the corporation’s secrecy and works to help survivors escape.', image:'https://img.gamewith.jp/article/thumbnail/rectangle_l/194602.png?date=1585844329', imagePosition:'50% 30%', incidents:['Raccoon City'], affiliations:['U.B.C.S.'] },
    { id:'rebecca', file:'STARS-014', name:'Rebecca Chambers', role:'S.T.A.R.S. Bravo Team', status:'Active', first:'Resident Evil 0', summary:'A gifted medic and scientist whose encounter with Umbrella begins before the Spencer Mansion incident.', bio:'Rebecca survives the Ecliptic Express and Umbrella Training Facility incidents before joining the surviving S.T.A.R.S. members at the Spencer Mansion.', image:'https://cdn.capcom-unity.com/capcom-unity.com/user/harrisony/resident_evil/re0_comparison_screens/c015ad2c341013311eb9448b1a0c0eec.png?v=214060', imagePosition:'35% 40%', incidents:['Ecliptic Express','Spencer Mansion'], affiliations:['S.T.A.R.S.'] }
  ],
  bows: [
    { code:'BOW-001', name:'Tyrant T-002', type:'Tyrant', threat:'Severe', source:'T-Virus', debut:'Resident Evil', summary:'An early humanoid B.O.W. engineered for combat performance and extreme resilience.' },
    { code:'BOW-002', name:'Hunter', type:'Hunter', threat:'High', source:'T-Virus', debut:'Resident Evil', summary:'A reptilian combat organism designed to outperform standard infected subjects.' },
    { code:'BOW-003', name:'Licker', type:'Mutant', threat:'High', source:'T-Virus', debut:'Resident Evil 2', summary:'An advanced mutation recognized by exposed brain tissue, elongated tongue and wall-crawling mobility.' },
    { code:'BOW-004', name:'Mr. X / T-00', type:'Tyrant', threat:'Severe', source:'T-Virus', debut:'Resident Evil 2', summary:'A trench-coated Tyrant deployed into Raccoon City to pursue mission objectives with relentless persistence.' },
    { code:'BOW-005', name:'Nemesis-T Type', type:'Nemesis', threat:'Critical', source:'NE-α / T-Virus', debut:'Resident Evil 3', summary:'A specialized Tyrant augmented with a parasite and tasked with eliminating surviving S.T.A.R.S. members.' },
    { code:'BOW-006', name:'Regenerator', type:'Plaga Host', threat:'Severe', source:'Las Plagas', debut:'Resident Evil 4', summary:'A laboratory-created Plaga host capable of rapidly regenerating otherwise catastrophic damage.' },
    { code:'BOW-007', name:'Uroboros', type:'Viral Organism', threat:'Critical', source:'Uroboros Virus', debut:'Resident Evil 5', summary:'An unstable viral organism producing massive black tendril-like growths in incompatible hosts.' },
    { code:'BOW-008', name:'Molded', type:'Fungal B.O.W.', threat:'High', source:'Mutamycete', debut:'Resident Evil 7', summary:'Humanoid fungal creatures generated through Mold infection and biomass.' },
    { code:'BOW-009', name:'Varcolac', type:'Lycan Variant', threat:'Severe', source:'Cadou / Mold', debut:'Resident Evil Village', summary:'A massive lycanthropic creature associated with the Village incident.' }
  ],
  timeline: [
    { year:'1960s', title:'Origins of Umbrella', text:'Research into unusual viral organisms lays the groundwork for the corporation and its biological-weapons programs.' },
    { year:'July 1998', title:'Arklay Mountains Incident', text:'S.T.A.R.S. investigates murders near Raccoon City and uncovers experiments connected to the Spencer Mansion.' },
    { year:'Sep. 1998', title:'Raccoon City Outbreak', text:'The infection spreads through the city, producing one of the defining biological disasters of the franchise.' },
    { year:'2004', title:'Umbrella Falls', text:'The original corporation collapses, but its research and biological weapons continue circulating.' },
    { year:'2009', title:'Kijuju Incident', text:'B.S.A.A. forces confront a major Uroboros outbreak and the endgame of Albert Wesker.' },
    { year:'2012–13', title:'Global C-Virus Attacks', text:'Multiple international incidents demonstrate the worldwide scale of organized bioterrorism.' },
    { year:'2017', title:'Baker Estate', text:'A missing-person search uncovers a Mold-based bioweapon and the E-series project.' },
    { year:'2021', title:'Village Incident', text:'The Winters case expands into a remote European settlement tied to the origin of the Mold research.' }
  ],
  pathogens: [
    { code:'SPECIMEN // T', name:'T-Virus', family:'Progenitor-derived', level:'Red', text:'One of Umbrella’s most infamous viral weapons, associated with mass infection, mutation and numerous B.O.W. projects.' },
    { code:'SPECIMEN // G', name:'G-Virus', family:'Golgotha', level:'Crimson', text:'A highly unstable mutagen capable of producing rapid, extreme biological changes and unusual reproductive behavior.' },
    { code:'SPECIMEN // PLAGA', name:'Las Plagas', family:'Parasite', level:'Amber', text:'Parasitic organisms capable of controlling hosts while preserving many higher cognitive functions.' },
    { code:'SPECIMEN // URO', name:'Uroboros', family:'Progenitor-derived', level:'Black', text:'A selective virus intended to trigger radical mutation, with catastrophic results in incompatible hosts.' },
    { code:'SPECIMEN // C', name:'C-Virus', family:'Chrysalid', level:'Orange', text:'A mutagenic weapon associated with rapid transformation, cocoons and widely varied infected forms.' },
    { code:'SPECIMEN // MOLD', name:'Mutamycete', family:'Fungal', level:'White', text:'A fungal organism capable of infection, regeneration and shared neurological connections across hosts.' }
  ],
  factions: [
    { abbr:'UMB', name:'Umbrella Corporation', text:'A pharmaceutical and biotechnology giant whose secret research programs drive many of the earliest disasters.' },
    { abbr:'S.T.', name:'S.T.A.R.S.', text:'Raccoon City’s Special Tactics and Rescue Service, whose members become some of Umbrella’s earliest major opponents.' },
    { abbr:'B.S.', name:'B.S.A.A.', text:'An international counter-bioterror organization formed to respond to the worldwide spread of biological weapons.' },
    { abbr:'RPD', name:'R.P.D.', text:'The Raccoon Police Department becomes one of the central battlegrounds during the 1998 citywide outbreak.' },
    { abbr:'TRS', name:'TerraSave', text:'A non-governmental organization focused on assisting victims of bioterrorism and biological disasters.' }
  ],
  locations: [
    { code:'UNITED STATES // 1998', name:'Raccoon City', note:'Ground zero for the franchise’s most infamous urban outbreak.', image:'https://cdn.capcom-unity.com/2026/02/Raccoon-City-lovers_nero-Final-1024x576.jpg' },
    { code:'ARKLAY MOUNTAINS', name:'Spencer Mansion', note:'The isolated estate concealing Umbrella’s underground laboratory network.', image:'https://cdn.capcom-unity.com/capcom-unity.com/user/brelston/remake/2a1a45232c7c234f610ec567611dd78a.jpg?v=202200' },
    { code:'RACCOON CITY', name:'R.P.D.', note:'A converted museum that becomes a fortress for survivors during the outbreak.', image:'https://cdn.capcom-unity.com/2026/02/Raccoon-City-Photo_Resume-Final-1024x576.jpg' },
    { code:'EUROPE', name:'The Village', note:'A remote settlement linked to Las Plagas and Los Illuminados.', image:'https://cdn.shazoo.ru/520412_GqbmSPXIJm_resident_evil.jpg' },
    { code:'LOUISIANA', name:'Baker Estate', note:'A decaying rural property consumed by a Mold-based biological incident.', image:'https://cdn.mobygames.com/screenshots/7959441-resident-evil-7-biohazard-banned-footage-vol2-playstation-4-daug.jpg' }
  ],
  mapPoints: [
    { id:'rpd', label:'R.P.D.', x:31, y:31, risk:'SEVERE', title:'Raccoon Police Department', text:'A key refuge and battleground during the September 1998 outbreak. Beneath it, survivors discover routes tied to Umbrella infrastructure.' },
    { id:'hospital', label:'Hospital', x:69, y:31, risk:'HIGH', title:'Spencer Memorial Hospital', text:'Medical facilities become overrun as the infection spreads, turning emergency treatment zones into quarantine failures.' },
    { id:'orphanage', label:'Orphanage', x:77, y:58, risk:'HIGH', title:'Raccoon City Orphanage', text:'A seemingly ordinary institution hiding connections to Umbrella-linked experimentation.' },
    { id:'lab', label:'NEST', x:52, y:76, risk:'CRITICAL', title:'NEST Laboratory', text:'An underground Umbrella research complex containing high-value viral research and dangerous experimental subjects.' },
    { id:'subway', label:'Subway', x:24, y:67, risk:'ELEVATED', title:'Subway Network', text:'One of the few potential evacuation paths during the citywide disaster, repeatedly compromised by infected creatures.' },
    { id:'clocktower', label:'Clock Tower', x:53, y:43, risk:'SEVERE', title:'St. Michael Clock Tower', text:'A recognizable city landmark and a major navigation point during the collapse of Raccoon City.' }
  ],
  media: [
    { title:'R.P.D. in the Rain', credit:'Capcom Snapshots / Photo_Resume', source:'Capcom-hosted community screenshot', image:'https://cdn.capcom-unity.com/2026/02/Raccoon-City-Photo_Resume-Final-1024x576.jpg' },
    { title:'Raccoon City Burns', credit:'Capcom Snapshots / lovers_nero', source:'Capcom-hosted community screenshot', image:'https://cdn.capcom-unity.com/2026/02/Raccoon-City-lovers_nero-Final-1024x576.jpg' },
    { title:'Leon S. Kennedy', credit:'Capcom Snapshots / iryukxx', source:'Capcom-hosted community screenshot', image:'https://cdn.capcom-unity.com/2023/11/Leon-Claire-iryukxx-Final-1024x1024.jpg' },
    { title:'Claire at the R.P.D.', credit:'Capcom Snapshots / juli__gamer', source:'Capcom-hosted community screenshot', image:'https://cdn.capcom-unity.com/2023/11/Leon-Claire-Juli__Gamer-Final-1024x754.jpg' },
    { title:'After Raccoon City', credit:'Capcom Snapshots / smthvalentine', source:'Capcom-hosted community screenshot', image:'https://cdn.capcom-unity.com/2023/11/Leon-Claire-smthvalentine-Final-1024x576.jpg' }
  ]
};

(() => {
  const data = window.RE_ARCHIVE;
  const bowIds = {'Tyrant T-002':'tyrant-t002','Hunter':'hunter','Licker':'licker','Mr. X / T-00':'mr-x','Nemesis-T Type':'nemesis','Regenerator':'regenerator','Uroboros':'uroboros','Molded':'molded','Varcolac':'varcolac'};
  const pathogenIds = {'T-Virus':'t-virus','G-Virus':'g-virus','Las Plagas':'las-plagas','Uroboros':'uroboros-virus','C-Virus':'c-virus','Mutamycete':'mutamycete'};
  const locationIds = {'Raccoon City':'raccoon-city','Spencer Mansion':'spencer-mansion','R.P.D.':'rpd','The Village':'village','Baker Estate':'baker-estate'};
  data.bows.forEach((entry) => { entry.id = bowIds[entry.name]; });
  data.pathogens.forEach((entry) => { entry.id = pathogenIds[entry.name]; });
  data.locations.forEach((entry) => { entry.id = locationIds[entry.name]; });
  const meta = {
    re0:{release:'November 2002',setting:'Arklay Mountains / Ecliptic Express',overview:'S.T.A.R.S. Bravo Team medic Rebecca Chambers and convicted former Marine Billy Coen uncover an Umbrella training operation while surviving the Ecliptic Express disaster.',characterIds:['rebecca'],bowIds:['hunter'],pathogenIds:['t-virus'],locationIds:[],incidentFacts:['Bravo Team enters the Arklay investigation before Alpha Team.','The Ecliptic Express and training facility expose early Umbrella experiments.','Rebecca survives the incident and later reaches the Spencer Mansion.']},
    re1:{release:'March 1996',setting:'Arklay Mountains / Spencer Mansion',overview:'S.T.A.R.S. Alpha Team searches for Bravo Team and discovers an isolated mansion hiding Umbrella laboratories, infected researchers, and engineered B.O.W.s.',characterIds:['jill','chris','wesker','rebecca'],bowIds:['tyrant-t002','hunter'],pathogenIds:['t-virus'],locationIds:['spencer-mansion'],incidentFacts:['Alpha Team is forced into the Spencer Mansion after an attack outside.','Hidden laboratories reveal Umbrella’s T-Virus research.','The mansion incident exposes Albert Wesker’s connection to Umbrella.']},
    re2:{release:'January 1998',setting:'Raccoon City / R.P.D.',overview:'Rookie officer Leon S. Kennedy and Claire Redfield arrive during Raccoon City’s collapse and uncover the G-Virus crisis beneath the police department.',characterIds:['leon','claire','ada'],bowIds:['licker','mr-x'],pathogenIds:['t-virus','g-virus'],locationIds:['raccoon-city','rpd'],incidentFacts:['Leon and Claire enter Raccoon City during the citywide outbreak.','The R.P.D. becomes a major survivor stronghold and battleground.','Umbrella’s underground facilities connect the outbreak to G-Virus research.']},
    re3:{release:'September 1999',setting:'Raccoon City',overview:'Jill Valentine attempts to escape Raccoon City while Umbrella deploys Nemesis to eliminate surviving S.T.A.R.S. members.',characterIds:['jill','carlos'],bowIds:['nemesis'],pathogenIds:['t-virus'],locationIds:['raccoon-city'],incidentFacts:['Jill is pursued through the city by Nemesis-T Type.','Carlos Oliveira and U.B.C.S. survivors become unlikely allies.','Raccoon City is ultimately destroyed to contain the outbreak.']},
    recv:{release:'February 2000',setting:'Rockfort Island / Antarctica',overview:'Claire Redfield’s search for Chris leads through an Umbrella prison complex, the Ashford family legacy, and another confrontation with Albert Wesker.',characterIds:['claire','chris','wesker'],bowIds:[],pathogenIds:['t-virus'],locationIds:[],incidentFacts:['Claire is captured while investigating Umbrella in Europe.','The Rockfort Island outbreak exposes the Ashford family’s experiments.','Chris and Claire reunite while Wesker pursues Umbrella research.']},
    re4:{release:'January 2005',setting:'Rural Spain',overview:'Federal agent Leon S. Kennedy searches for the president’s daughter and uncovers Los Illuminados, a cult using Las Plagas parasites to control hosts.',characterIds:['leon','ada'],bowIds:['regenerator'],pathogenIds:['las-plagas'],locationIds:[],incidentFacts:['Leon enters rural Europe on a rescue mission.','Los Illuminados uses Las Plagas to control villagers and soldiers.','Ada Wong’s mission intersects with Leon’s investigation.']},
    re5:{release:'March 2009',setting:'Kijuju Autonomous Zone',overview:'Chris Redfield and B.S.A.A. agent Sheva Alomar investigate a bioterror outbreak tied to Tricell, Uroboros, and Albert Wesker.',characterIds:['chris','wesker'],bowIds:['uroboros'],pathogenIds:['uroboros-virus'],locationIds:[],incidentFacts:['The B.S.A.A. enters Kijuju during an escalating bioterror incident.','Uroboros becomes central to Wesker’s plan.','Chris confronts Wesker in the culmination of their long conflict.']},
    re6:{release:'October 2012',setting:'Tall Oaks / Lanshiang / Edonia',overview:'Multiple campaigns follow Leon, Chris, Ada, and other operatives through a coordinated global bioterror crisis involving the C-Virus.',characterIds:['leon','chris','ada'],bowIds:[],pathogenIds:['c-virus'],locationIds:[],incidentFacts:['A Tall Oaks outbreak escalates into an international crisis.','Separate campaigns converge around the C-Virus conspiracy.','Bioterror attacks span multiple continents and organizations.']},
    re7:{release:'January 2017',setting:'Dulvey, Louisiana / Baker Estate',overview:'Ethan Winters searches for Mia at the Baker estate and uncovers a Mold-based bioweapon tied to the E-series project.',characterIds:['ethan'],bowIds:['molded'],pathogenIds:['mutamycete'],locationIds:['baker-estate'],incidentFacts:['Ethan arrives at the Baker property after receiving a message from Mia.','The family and surrounding organisms are linked through the Mold.','The incident reveals the E-series bioweapon program.']},
    re8:{release:'May 2021',setting:'Remote European Village',overview:'Ethan Winters enters an isolated village while searching for his daughter and uncovers the deeper history of the Mold and Mother Miranda’s experiments.',characterIds:['ethan','chris'],bowIds:['varcolac'],pathogenIds:['mutamycete'],locationIds:['village'],incidentFacts:['Ethan is drawn into a village controlled by four powerful lords.','The Megamycete links the village experiments to earlier Mold research.','Chris Redfield’s unit operates in the area during the final phase of the incident.']},
    re2r:{release:'January 2019',setting:'Raccoon City / R.P.D.',overview:'A modern reimagining of the 1998 Raccoon City disaster follows Leon and Claire through the R.P.D., sewers, and Umbrella’s underground NEST facility.',characterIds:['leon','claire','ada'],bowIds:['licker','mr-x'],pathogenIds:['t-virus','g-virus'],locationIds:['raccoon-city','rpd'],incidentFacts:['Leon and Claire arrive during Raccoon City’s collapse.','Mr. X relentlessly pursues survivors through the police station.','The NEST facility reveals the outbreak’s connection to G-Virus research.']},
    re4r:{release:'March 2023',setting:'Rural Spain',overview:'Leon’s rescue mission returns in a darker reimagining centered on Las Plagas, Los Illuminados, and the struggle to extract Ashley Graham.',characterIds:['leon','ada'],bowIds:['regenerator'],pathogenIds:['las-plagas'],locationIds:[],incidentFacts:['Leon enters an isolated region while searching for Ashley Graham.','Las Plagas infection drives the cult’s control over the population.','Ada’s objectives repeatedly intersect with Leon’s mission.']}
  };
  data.games.forEach((game) => Object.assign(game, meta[game.id], {heroImage:game.image, heroPosition:game.imagePosition, weaponIds:[]}));
})();

(() => {
  const data = window.RE_ARCHIVE;
  const H = {re1:'https://cdn.akamai.steamstatic.com/steam/apps/4249100/header.jpg',recv:'https://i.jeuxactus.com/datas/jeux/r/e/resident-evil-code-veronica-x/xl/resident-evil-code-4e26073a612d4.jpg',re2:'https://cdn.akamai.steamstatic.com/steam/apps/883710/header.jpg',re4:'https://cdn.akamai.steamstatic.com/steam/apps/2050650/header.jpg',re5:'https://cdn.akamai.steamstatic.com/steam/apps/21690/header.jpg',re6:'https://cdn.akamai.steamstatic.com/steam/apps/221040/header.jpg',re7:'https://cdn.akamai.steamstatic.com/steam/apps/418370/header.jpg',re8:'https://cdn.akamai.steamstatic.com/steam/apps/1196590/header.jpg'};
  data.weapons = [
    {id:'samurai-edge',name:'Samurai Edge',class:'Handgun',ammo:'9mm',summary:'A customized S.T.A.R.S. sidearm associated with the unit’s veteran operatives.',image:H.re1,imagePosition:'50% 48%',gameIds:['re0','re1','re3'],characterIds:['jill','chris','rebecca'],variants:['Jill Model','Chris Model','Albert Model'],attachments:[]},
    {id:'classic-shotgun',name:'Shotgun',class:'Shotgun',ammo:'12-gauge shells',summary:'A close-range long gun used throughout the Spencer Mansion incident.',image:H.re1,imagePosition:'50% 48%',gameIds:['re1'],characterIds:['jill','chris'],variants:[],attachments:[]},
    {id:'grenade-launcher',name:'Grenade Launcher',class:'Launcher',ammo:'Grenade rounds',summary:'A heavy utility launcher used against clustered infected and larger B.O.W. threats.',image:H.re1,imagePosition:'50% 48%',gameIds:['re1','re3'],characterIds:['jill'],variants:[],attachments:[]},
    {id:'magnum-revolver',name:'Magnum Revolver',class:'Magnum',ammo:'Magnum rounds',summary:'A high-powered sidearm reserved for the archive’s most dangerous encounters.',image:H.re1,imagePosition:'50% 48%',gameIds:['re1'],characterIds:['jill','chris'],variants:[],attachments:[]},
    {id:'bow-gun',name:'Bow Gun',class:'Special',ammo:'Bow Gun arrows',summary:'Claire’s compact projectile weapon during the Rockfort Island incident.',image:H.recv,imagePosition:'50% 28%',gameIds:['recv'],characterIds:['claire'],variants:[],attachments:[]},
    {id:'matilda',name:'Matilda',class:'Handgun',ammo:'9mm handgun ammo',summary:'Leon’s dependable polymer-frame handgun, adaptable through multiple custom parts.',image:'https://articles-img.sftcdn.net/auto-mapping-folder/sites/3/2019/01/matilda-1024x576.jpg',imagePosition:'50% 45%',gameIds:['re2','re2r'],characterIds:['leon'],variants:[],attachments:['High-Capacity Mag','Muzzle Brake','Gun Stock']},
    {id:'w870',name:'W-870',class:'Shotgun',ammo:'12-gauge shotgun shells',summary:'A sturdy pump-action shotgun favored for close-quarters stopping power.',image:'https://static.accelerated-ideas.com/news/images/resident_evil_2_ps4_shotgun.jpg',imagePosition:'50% 45%',gameIds:['re2','re2r'],characterIds:['leon'],variants:[],attachments:['Long Barrel','Shotgun Stock']},
    {id:'lightning-hawk',name:'Lightning Hawk',class:'Magnum',ammo:'.50 AE MAG',summary:'A powerful gas-operated magnum that combines accuracy with exceptional stopping power.',image:'https://cdn.mos.cms.futurecdn.net/ahKrXHyJTbUHGKQjgawc3V.jpg',imagePosition:'50% 50%',gameIds:['re2','re2r'],characterIds:['leon'],variants:[],attachments:['Long Barrel','Red Dot Sight']},
    {id:'combat-knife',name:'Combat Knife',class:'Melee',ammo:'None',summary:'A survival knife used for emergency defense and utility during the Raccoon City incident.',image:H.re2,imagePosition:'50% 46%',gameIds:['re2','re2r'],characterIds:['leon','claire'],variants:[],attachments:[]},
    {id:'chemical-flamethrower',name:'Chemical Flamethrower',class:'Special',ammo:'Fuel',summary:'An industrial flamethrower repurposed as a high-risk anti-B.O.W. weapon.',image:H.re2,imagePosition:'50% 46%',gameIds:['re2r'],characterIds:['leon'],variants:[],attachments:['Regulator']},
    {id:'sg09r',name:'SG-09 R',class:'Handgun',ammo:'Handgun ammo',summary:'Leon’s customized service handgun for the reimagined Los Illuminados mission.',image:'https://cdn11.bigcommerce.com/s-9mcepdq780/images/stencil/1280x1280/products/2618/11267/7__43469.1712926369.jpg?c=2',imagePosition:'50% 35%',gameIds:['re4r'],characterIds:['leon'],variants:[],attachments:['Laser Sight']},
    {id:'riot-gun',name:'Riot Gun',class:'Shotgun',ammo:'Shotgun shells',summary:'A semi-automatic shotgun built around controllable recoil and strong mid-range performance.',image:'https://cdn.mos.cms.futurecdn.net/amXSAp67dkjeBTcPEktaJG.jpg',imagePosition:'50% 45%',gameIds:['re4','re4r'],characterIds:['leon'],variants:[],attachments:[]},
    {id:'broken-butterfly',name:'Broken Butterfly',class:'Magnum',ammo:'Magnum ammo',summary:'A vintage magnum revolver with extreme stopping power.',image:'https://cdn.mos.cms.futurecdn.net/zVdERjyjm6dJjZK2QTb5xF.jpg',imagePosition:'50% 45%',gameIds:['re4','re4r'],characterIds:['leon'],variants:[],attachments:[]},
    {id:'stingray',name:'Stingray',class:'Rifle',ammo:'Rifle ammo',summary:'A semi-automatic rifle designed for precision fire at range.',image:'https://img.playstationtrophies.org/images/monthly_2023_03/guide/residentevil4_20230324112729_299f7c45-c6a6-4e40-b95e-7ebc9a06913d_l.jpg',imagePosition:'50% 45%',gameIds:['re4r'],characterIds:['leon'],variants:[],attachments:['High-Power Scope','Biosensor Scope']},
    {id:'tmp',name:'TMP',class:'SMG',ammo:'Submachine gun ammo',summary:'A compact submachine gun that trades precision for a high rate of fire.',image:H.re4,imagePosition:'50% 43%',gameIds:['re4','re4r'],characterIds:['leon'],variants:[],attachments:['TMP Stock']},
    {id:'rocket-launcher',name:'Rocket Launcher',class:'Launcher',ammo:'Rocket',summary:'A single-purpose heavy weapon intended for the most dangerous targets.',image:H.re4,imagePosition:'50% 43%',gameIds:['re4','re4r'],characterIds:['leon'],variants:['Infinite Rocket Launcher'],attachments:[]},
    {id:'m92f',name:'M92F',class:'Handgun',ammo:'Handgun ammo',summary:'A dependable B.S.A.A. sidearm used during the Kijuju incident.',image:H.re5,imagePosition:'50% 42%',gameIds:['re5'],characterIds:['chris'],variants:[],attachments:[]},
    {id:'ithaca-m37',name:'Ithaca M37',class:'Shotgun',ammo:'Shotgun shells',summary:'A pump-action shotgun suited to the dense close-quarters fighting in Kijuju.',image:H.re5,imagePosition:'50% 42%',gameIds:['re5'],characterIds:['chris'],variants:[],attachments:[]},
    {id:'sig556',name:'SIG 556',class:'Rifle',ammo:'Rifle ammo',summary:'A select-fire rifle used by B.S.A.A. operatives during the African bioterror incident.',image:H.re5,imagePosition:'50% 42%',gameIds:['re5'],characterIds:['chris'],variants:[],attachments:[]},
    {id:'rpg7',name:'RPG-7',class:'Launcher',ammo:'Rocket',summary:'A heavy anti-armor launcher used against extreme B.O.W. threats.',image:H.re5,imagePosition:'50% 42%',gameIds:['re5'],characterIds:['chris'],variants:[],attachments:[]},
    {id:'wing-shooter',name:'Wing Shooter',class:'Handgun',ammo:'9mm handgun ammo',summary:'Leon’s paired sidearms during the global C-Virus crisis.',image:H.re6,imagePosition:'50% 44%',gameIds:['re6'],characterIds:['leon'],variants:[],attachments:[]},
    {id:'assault-rifle-for-special-tactics',name:'Assault Rifle for Special Tactics',class:'Rifle',ammo:'5.56mm NATO',summary:'A tactical rifle associated with Chris Redfield’s B.S.A.A. campaign.',image:H.re6,imagePosition:'50% 44%',gameIds:['re6'],characterIds:['chris'],variants:[],attachments:[]},
    {id:'m19',name:'M19',class:'Handgun',ammo:'Handgun ammo',summary:'A compact handgun found during Ethan Winters’ search through the Baker estate.',image:'https://gameranx.com/wp-content/uploads/2017/01/RESIDENT-EVIL-7-biohazard_20170127235906-1.jpg',imagePosition:'50% 45%',gameIds:['re7'],characterIds:['ethan'],variants:[],attachments:[]},
    {id:'albert01r',name:'Albert-01R',class:'Handgun',ammo:'Handgun ammo',summary:'A powerful anti-B.O.W. handgun derived from equipment used late in the Baker incident.',image:H.re7,imagePosition:'50% 48%',gameIds:['re7'],characterIds:['ethan'],variants:[],attachments:[]},
    {id:'lemi',name:'LEMI',class:'Handgun',ammo:'Handgun ammo',summary:'Ethan’s early sidearm during the Village incident.',image:H.re8,imagePosition:'50% 42%',gameIds:['re8'],characterIds:['ethan'],variants:[],attachments:['Recoil Compensator','High-Capacity Mag']},
    {id:'m1897',name:'M1897',class:'Shotgun',ammo:'Shotgun shells',summary:'A pump-action shotgun recovered early in the Village incident.',image:'https://www.egames.news/img/2021/05/15/resident_evil_village_cxmo_conseguir_la_escopeta_m1897.png?__scale=w%3A480',imagePosition:'50% 50%',gameIds:['re8'],characterIds:['ethan'],variants:[],attachments:[]},
    {id:'f2-rifle',name:'F2 Rifle',class:'Rifle',ammo:'Rifle ammo',summary:'A bolt-action rifle used for long-range precision in the mountain village.',image:H.re8,imagePosition:'50% 42%',gameIds:['re8'],characterIds:['ethan'],variants:[],attachments:['High Magnification Scope','High-Capacity Mag']},
    {id:'wolfsbane',name:'M1851 Wolfsbane',class:'Magnum',ammo:'Magnum ammo',summary:'A high-caliber revolver associated with the strongest threats in the Village incident.',image:H.re8,imagePosition:'50% 42%',gameIds:['re8'],characterIds:['ethan'],variants:[],attachments:['Long Barrel']}
  ];
  data.games.forEach((game) => { game.weaponIds = data.weapons.filter((weapon) => weapon.gameIds.includes(game.id)).map((weapon) => weapon.id); });
})();
